resolver: lts-3.16

flags:
  homeworlds:
    web: False

packages:
  - location: '.'
  - extra-dep: true
    location:
      git: https://github.com/ryantrinkle/reflex-dom.git
      commit: f4dbdd799260bc203f7f5cdce18362cb896f6d57

extra-deps:
  - ghcjs-dom-0.2.3.0
  - ref-tf-0.4
  - reflex-0.3.2
  - these-0.6.1.0
  - webkitgtk3-0.14.1.0
  - webkitgtk3-javascriptcore-0.13.1.0
  - base-noprelude-4.8.1.0
