#!/usr/bin/env bash

set -e

./script/bootstrap
./script/build

export STACK_YAML=stack.ghcjs.yaml
stack setup
stack build

mkdir -p dist

cp .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/homeworlds/* ./dist
cp .stack-work/dist/x86_64-osx/Cabal-1.22.4.0_ghcjs/build/homeworlds/homeworlds.jsexe/* ./dist
